# Secrets are configured in the repo settings > Secrets and varaibles > Actions

name: secrets workflow

on:
  push:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use secrets
        run: echo "The secret is ${{ secrets.My_Secret }}"
        # The workflow will run this command, but GitHub will not expose the secret value
